# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [2]:
import numpy as np
import pandas as pd

In [38]:
data2 = pd.read_csv('minutes_n_ingredients.csv')
data2.head()

id  minutes  n_ingredients
0  127244       60             16
1   23891       25              7
2   94746       10              6
3   67660        5              6
4  157911       60             14

In [111]:
data = np.loadtxt('minutes_n_ingredients.csv', dtype = 'int32', delimiter=',', skiprows=1)
data[:5]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]])

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [112]:
np.mean(data[:,1:], axis = 0)

array([2.16010017e+04, 9.05528000e+00])

In [113]:
np.median(data[:,1:], axis = 0)

array([40.,  9.])

In [114]:
np.max(data[:, 1:], axis = 0)

array([2147483647,         39])

In [115]:
np.min(data[:, 1:], axis = 0)

array([0, 1])

3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [116]:
q = np.quantile(data[:, 1], q = 0.75)
data[:, 1] = data[:, 1].clip(max = q)
data

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [ 81993,     65,     14]])

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [117]:
sum(data[:, 1] == 0)

479

In [118]:
cop = data.copy()
cop[cop[:,1] == 0] = 1
cop

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [ 81993,     65,     14]])

In [119]:
sum(cop[:, 1] == 0)

0

In [120]:
data[data[:,1] == 0] = 1

5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [121]:
len(np.unique(data[:,0]))

99522

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [122]:
len(np.unique(data[:,-1]))

37

In [123]:
np.unique(data[:,0])

array([     1,     38,     41, ..., 537458, 537485, 537671])

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [124]:
arr_ing = data[data[:, -1] <= 5]
arr_ing

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]])

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [125]:
mead_mean = data[:,-1]/data[:,1]
max(mead_mean)

23.0

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [126]:
data[data[:,1].argsort()[-100:]][:,-1].mean()


9.96

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [127]:
data[np.random.choice(100000, size = 10),:]

array([[106820,     65,     11],
       [429534,     15,     10],
       [ 72447,     55,      9],
       [ 93022,     30,     10],
       [390771,     65,     18],
       [ 90042,     45,     12],
       [136339,     17,      9],
       [ 48167,     55,     11],
       [ 61782,     15,      8],
       [116907,     65,     10]])

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [128]:
len(data[data[:,-1] < data[:,-1].mean()]) / 100000

0.58989

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [156]:
cop = data.copy()
cop

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [ 81993,     65,     14]])

In [157]:
data2 = np.all([cop[:,-2] <= 20, cop[:,-1] <= 5], axis = 0) * 1
data2 = np.append(cop, data2[:, np.newaxis], axis = 1)
data2

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,     65,     14,      0]])

13. Выведите процент "простых" рецептов в датасете

In [158]:
sum(data2[:,-1]) / len(data2[:,-1]) * 100

9.943

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [164]:
a = data2[data2[:,1] < 10]
b = data2[np.all([data2[:,1] >= 10, data2[:,1] < 20], axis = 0)]
c = data2[data2[:,1] >= 20]

In [168]:
data3 = np.array([a, b, c])
data3

<ipython-input-168-ea60b994ee48>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  data3 = np.array([a, b, c])


array([array([[ 67660,      5,      6,      0],
       [366174,      7,      9,      0],
       [204134,      5,      3,      1],
       ...,
       [420725,      5,      3,      1],
       [     1,      1,      1,      1],
       [370915,      5,      4,      1]]),
       array([[ 94746,     10,      6,      0],
       [ 33941,     18,      9,      0],
       [446597,     15,      5,      1],
       ...,
       [ 44120,     17,      5,      1],
       [ 60756,     15,      5,      1],
       [128811,     15,      4,      1]]),
       array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [157911,     60,     14,      0],
       ...,
       [287943,     65,     15,      0],
       [498432,     65,     15,      0],
       [ 81993,     65,     14,      0]])], dtype=object)